/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeveloperService } from "../developer.service";
import { DeveloperCreateInput } from "./DeveloperCreateInput";
import { Developer } from "./Developer";
import { DeveloperFindManyArgs } from "./DeveloperFindManyArgs";
import { DeveloperWhereUniqueInput } from "./DeveloperWhereUniqueInput";
import { DeveloperUpdateInput } from "./DeveloperUpdateInput";
import { CollaborationInvitationFindManyArgs } from "../../collaborationInvitation/base/CollaborationInvitationFindManyArgs";
import { CollaborationInvitation } from "../../collaborationInvitation/base/CollaborationInvitation";
import { CollaborationInvitationWhereUniqueInput } from "../../collaborationInvitation/base/CollaborationInvitationWhereUniqueInput";

export class DeveloperControllerBase {
  constructor(protected readonly service: DeveloperService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Developer })
  async createDeveloper(
    @common.Body() data: DeveloperCreateInput
  ): Promise<Developer> {
    return await this.service.createDeveloper({
      data: data,
      select: {
        bio: true,
        createdAt: true,
        email: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Developer] })
  @ApiNestedQuery(DeveloperFindManyArgs)
  async developers(@common.Req() request: Request): Promise<Developer[]> {
    const args = plainToClass(DeveloperFindManyArgs, request.query);
    return this.service.developers({
      ...args,
      select: {
        bio: true,
        createdAt: true,
        email: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async developer(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    const result = await this.service.developer({
      where: params,
      select: {
        bio: true,
        createdAt: true,
        email: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() data: DeveloperUpdateInput
  ): Promise<Developer | null> {
    try {
      return await this.service.updateDeveloper({
        where: params,
        data: data,
        select: {
          bio: true,
          createdAt: true,
          email: true,
          id: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    try {
      return await this.service.deleteDeveloper({
        where: params,
        select: {
          bio: true,
          createdAt: true,
          email: true,
          id: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/collaborationInvitations")
  @ApiNestedQuery(CollaborationInvitationFindManyArgs)
  async findCollaborationInvitations(
    @common.Req() request: Request,
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<CollaborationInvitation[]> {
    const query = plainToClass(
      CollaborationInvitationFindManyArgs,
      request.query
    );
    const results = await this.service.findCollaborationInvitations(params.id, {
      ...query,
      select: {
        createdAt: true,

        developer: {
          select: {
            id: true,
          },
        },

        id: true,

        project: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/collaborationInvitations")
  async connectCollaborationInvitations(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: CollaborationInvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      collaborationInvitations: {
        connect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/collaborationInvitations")
  async updateCollaborationInvitations(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: CollaborationInvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      collaborationInvitations: {
        set: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/collaborationInvitations")
  async disconnectCollaborationInvitations(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: CollaborationInvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      collaborationInvitations: {
        disconnect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }
}
